Repository ibrahimraimi/ui, pull requests merged in 2025-04, with the labels that each got.

#2 feat: Add SEO metadata and site configuration
  src/routes/+layout.svelte
  static/og.png
Labels: enhancement

#9 feat(ui): implement Dialog component stories for Storybook
  src/lib/components/ui/dialog/dialog.stories.svelte
  src/lib/components/ui/dialog/dialog.svelte
  src/lib/components/ui/dialog/index.ts
Labels: enhancement

#10 docs: setup site documentation
  .cursor/rules/components.mdc
  .cursor/rules/documentation.mdc
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app.css
  src/app.html
  src/lib/components/AppHeader.svelte
  src/lib/components/CodeBlock.svelte
  src/lib/components/DocsSidebar.svelte
  src/lib/components/PackageManagerSelector.svelte
  src/lib/components/TableOfContents.svelte
  src/lib/components/ThemeToggle.svelte
  src/lib/components/sidebar-items.ts
  src/lib/mdsvex-layout.svelte
  src/lib/utils.ts
  src/routes/(app)/+layout.svelte
  src/routes/(app)/+page.svelte
  src/routes/(app)/components/+page.svelte
  src/routes/(app)/form-example/+page.svelte
  src/routes/(app)/page.svelte.test.ts
  src/routes/(documentation)/+layout.svelte
  src/routes/(documentation)/docs/+layout.svelte
  src/routes/(documentation)/docs/+page.svelte
  src/routes/(documentation)/docs/+page.ts
  src/routes/(documentation)/docs/[lang]/[slug]/+page.svelte
  src/routes/(documentation)/docs/[lang]/[slug]/+page.ts
  src/routes/(documentation)/docs/[slug]/+page.svelte
  src/routes/(documentation)/docs/[slug]/+page.ts
  src/routes/(documentation)/docs/content/en/button.svex
  src/routes/(documentation)/docs/content/en/introduction.svex
  src/routes/(documentation)/docs/content/es/introduction.svex
  src/routes/+layout.svelte
  svelte.config.js
Labels: documentation

#11 feat(deploy): notify Discord via SvelteKit API route on Netlify deploy success
  src/routes/api/netlify-webhook/+server.ts
Labels: enhancement, ci

#13 feat(layout): add Navbar and Footer components with improved layout structure
  src/lib/components/AppHeader.svelte
  src/lib/components/SiteFooter.svelte
  src/lib/components/SiteHeader.svelte
  src/routes/(documentation)/+layout.svelte
  src/routes/+layout.svelte
Labels: enhancement

#14 Tailwind CSS Upgrade and Configuration Changes
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  src/app.css
  src/lib/components/PackageManagerSelector.svelte
  src/lib/components/SiteHeader.svelte
  src/lib/components/ui/button/Button.svelte
  src/lib/components/ui/card/Card.svelte
  src/lib/components/ui/dialog/dialog-close.svelte
  src/lib/components/ui/dialog/dialog.svelte
  src/lib/components/ui/input/Input.svelte
  src/lib/components/ui/toasts/toast.svelte
  src/routes/(app)/+layout.svelte
  src/routes/(app)/+page.svelte
  src/routes/(documentation)/docs/[lang]/[slug]/+page.svelte
  src/routes/+layout.svelte
  tailwind.config.cjs
Labels: dependencies
